var splatoon = {
	modes:[
		'Turf War',
		'Splat Zones',
		'Tower Control',
		'Rainmaker',
		'Clam Blitz'],
	stages:[
		'Barnacle & Dime',
		'Bluefin Depot',
		'Brinewater Springs',
		'Crableg Capital',
		'Eeltail Alley',
		'Flounder Heights',
		'Hagglefish Market',
		'Hammerhead Bridge',
		'Humpback Pump Track',
		'Inkblot Art Academy',
		'Lemuria Hub',
		'Mahi-Mahi Resort',
		'MakoMart',
		'Manta Maria',
		'Marlin Airport',
		'Mincemeat Metalworks',
		'Museum d\'Alfonsino'
		'Robo ROM-en',
		'Scorch Gorge',
		'Shipshape Cargo Co.',
		'Sturgeon Shipyard',
		'Um\'ami Ruins'
		'Undertow Spillway'
		'Wahoo World'
	weapons:[
		{name:'Splattershot Jr.', subWeapon:'Splat Bomb', specialWeapon:'Big Bubbler'},
		
		headgear: [
			{name:'18K Aviators', mainAbility:'Last-Ditch Effort'},
  			{name:'Air Gills DX', mainAbility:'Tenacity'},
 			{name:'Annaki Charms', mainAbility:'Swim Speed Up'},
  			{name:'Annaki Mask', mainAbility:'Opening Gambit'},
  			{name:'Bamboo Hat', mainAbility:'Ink Saver (Main)'},
 			{name:'Beachcomber', mainAbility:'Opening Gambit'},
			{name:'BlobMob Mask', mainAbility:'Tenacity'},
			{name:'Bream-Brim Cap', mainAbility:'Grizz'},
			{name:'Bucket Hat', mainAbility:'Special Saver'},
			{name:'Cephalo Pods', mainAbility:'Ink Recovery Up'},
			{name:'Classic Bowler', mainAbility:'Run Speed Up'},
			{name:'Classic Straw Boater', mainAbility:'Special Power Up'},
			{name:'Designer Headphones', mainAbility:'Ink Saver (Sub)'},
			{name:'Double Egg Shades', mainAbility:'Last-Ditch Effort'},
			{name:'Face Visor', mainAbility:'Sub Resistance Up'},
			{name:'Firefin Facemask', mainAbility:'Run Speed Up'},
			{name:'FishFry Biscuit Bandana', mainAbility:'Special Power Up'},
			{name:'FishFry Visor', mainAbility:'Special Charge Up'},
  			{name:'Forge Mask', mainAbility:'Intensify Action'},
			{name:'Full-Moon Glasses', mainAbility:'Quick Super Jump'},
  			{name:'Glassless Glasses', mainAbility:'Quick Respawn'},
			{name:'Half-Rim Glasses', mainAbility:'Special Power Up'},
			{name:'Hero Mindset Replica', mainAbility:'Sub Power Up'},
			{name:'Hickory Work Cap', mainAbility:'Special Power Up'},
			{name:'Hockey Helmet', mainAbility:'Intensify Action'},
			{name:'Home-Team Catcher', mainAbility:'Ink Resistance Up'},
			{name:'Howdy Hat', mainAbility:'Sub Resistance Up'},
			{name:'Ink-Black Flap Cap', mainAbility:'Special Power Up'},
			{name:'Ink-Tinted Goggles', mainAbility:'Swim Speed Up'},
			{name:'Invisifloats', mainAbility:'Comeback'},
			{name:'Jean Dream Bucket', mainAbility:'Swim Speed Up'},
			{name:'Knitted Hat', mainAbility:'Ink Resistance Up'},
			{name:'Moto Shades', mainAbility:'Last-Ditch Effort'},
			{name:'Ocho OctoPhones', mainAbility:'Opening Gambit'},
			{name:'Party Hard Hat', mainAbility:'Quick Super Jump'},
			{name:'Pilot Goggles', mainAbility:'Sub Power Up'},
			{name:'Retro BluFocals', mainAbility:'Intensify Action'},
			{name:'Retro Framers', mainAbility:'Opening Gambit'},
			{name:'Splash Goggles', mainAbility:'Sub Resistance Up'},
			{name:'Squidband', mainAbility:'Quick Respawn'},
			{name:'Squidbeak Shield', mainAbility:'Sub Power Up'},
			{name:'Squidlife Headphones', mainAbility:'Ink Recovery Up'},
			{name:'Squidvader Cap', mainAbility:'Special Charge Up'},
			{name:'Streetstyle Cap', mainAbility:'Ink Saver (Sub)'
			{name:'Studio Headphones', mainAbility:'Ink Saver (Main)'},
			{name:'Swim Goggles', mainAbility:'Last-Ditch Effort'},
			{name:'Takoroka Mesh', mainAbility:'Sub Resistance Up'},
			{name:'Takoroka Visor', mainAbility:'Quick Super Jump'},
			{name:'Teddy Band', mainAbility:'Comeback'},
			{name:'Tennis Headband', mainAbility:'Comeback'},
			{name:'Tinted Shades', mainAbility:'Last-Ditch Effort'},
			{name:'Triple-Deck Specs', mainAbility:'Sub Power Up'},
			{name:'Urchins Cap', mainAbility:'Sub Power Up'},
			{name:'Wharfside Cap', mainAbility:'Tenacity'},
			{name:'White Headband', mainAbility:'Ink Recovery Up'},
			{name:'Winkle Stripe Helm', mainAbility:'Sub Resistance Up'},
			{name:'Woolly Urchins Classic', mainAbility:'Comeback'},
		],
		clothing: [
			
			{name:'Aloha Shirt', mainAbility:'Ink Recovery Up'},
			
		],
		shoes: [
			{name:'Acerola Rain Boots', mainAbility:'Run Speed Up'},
		],
	abilities: [
		'Comeback',
		'Drop Roller Up',
		'Haunt',
		'Ink Recovery Up',
		'Ink Resistance Up',
		'Ink Saver (Main)',
		'Ink Saver (Sub)',
		'Intensify Action'
		'Last-Ditch Effort',
		'Ninja Squid',
		'Object Shredder',
		'Opening Gambit',
		'Quick Respawn',
		'Quick Super Jump',
		'Respawn Punisher',
		'Run Speed Up',
		'Special Charge Up',
		'Special Power Up',
		'Special Saver',
		'Stealth Jump',
		'Swim Speed Up',
		'Tenacity',
		'Thermal Ink'],
		
	teamCombinations: [
		[0, 0, 0, 0, 1, 1, 1, 1],
		[0, 0, 0, 1, 0, 1, 1, 1],
		[0, 0, 0, 1, 1, 0, 1, 1],
		[0, 0, 0, 1, 1, 1, 0, 1],
		[0, 0, 0, 1, 1, 1, 1, 0],
		[0, 0, 1, 0, 0, 1, 1, 1],
		[0, 0, 1, 0, 1, 0, 1, 1],
		[0, 0, 1, 0, 1, 1, 0, 1],
		[0, 0, 1, 0, 1, 1, 1, 0],
		[0, 0, 1, 1, 0, 0, 1, 1],
		[0, 0, 1, 1, 0, 1, 0, 1],
		[0, 0, 1, 1, 0, 1, 1, 0],
		[0, 0, 1, 1, 1, 0, 0, 1],
		[0, 0, 1, 1, 1, 0, 1, 0],
		[0, 0, 1, 1, 1, 1, 0, 0],
		[0, 1, 0, 0, 0, 1, 1, 1],
		[0, 1, 0, 0, 1, 0, 1, 1],
		[0, 1, 0, 0, 1, 1, 0, 1],
		[0, 1, 0, 0, 1, 1, 1, 0],
		[0, 1, 0, 1, 0, 0, 1, 1],
		[0, 1, 0, 1, 0, 1, 0, 1],
		[0, 1, 0, 1, 0, 1, 1, 0],
		[0, 1, 0, 1, 1, 0, 0, 1],
		[0, 1, 0, 1, 1, 0, 1, 0],
		[0, 1, 0, 1, 1, 1, 0, 0],
		[0, 1, 1, 0, 0, 0, 1, 1],
		[0, 1, 1, 0, 0, 1, 0, 1],
		[0, 1, 1, 0, 0, 1, 1, 0],
		[0, 1, 1, 0, 1, 0, 0, 1],
		[0, 1, 1, 0, 1, 0, 1, 0],
		[0, 1, 1, 0, 1, 1, 0, 0],
		[0, 1, 1, 1, 0, 0, 0, 1],
		[0, 1, 1, 1, 0, 0, 1, 0],
		[0, 1, 1, 1, 0, 1, 0, 0],
		[0, 1, 1, 1, 1, 0, 0, 0],
		[1, 1, 1, 1, 0, 0, 0, 0],
		[1, 1, 1, 0, 1, 0, 0, 0],
		[1, 1, 1, 0, 0, 1, 0, 0],
		[1, 1, 1, 0, 0, 0, 1, 0],
		[1, 1, 1, 0, 0, 0, 0, 1],
		[1, 1, 0, 1, 1, 0, 0, 0],
		[1, 1, 0, 1, 0, 1, 0, 0],
		[1, 1, 0, 1, 0, 0, 1, 0],
		[1, 1, 0, 1, 0, 0, 0, 1],
		[1, 1, 0, 0, 1, 1, 0, 0],
		[1, 1, 0, 0, 1, 0, 1, 0],
		[1, 1, 0, 0, 1, 0, 0, 1],
		[1, 1, 0, 0, 0, 1, 1, 0],
		[1, 1, 0, 0, 0, 1, 0, 1],
		[1, 1, 0, 0, 0, 0, 1, 1],
		[1, 0, 1, 1, 1, 0, 0, 0],
		[1, 0, 1, 1, 0, 1, 0, 0],
		[1, 0, 1, 1, 0, 0, 1, 0],
		[1, 0, 1, 1, 0, 0, 0, 1],
		[1, 0, 1, 0, 1, 1, 0, 0],
		[1, 0, 1, 0, 1, 0, 1, 0],
		[1, 0, 1, 0, 1, 0, 0, 1],
		[1, 0, 1, 0, 0, 1, 1, 0],
		[1, 0, 1, 0, 0, 1, 0, 1],
		[1, 0, 1, 0, 0, 0, 1, 1],
		[1, 0, 0, 1, 1, 1, 0, 0],
		[1, 0, 0, 1, 1, 0, 1, 0],
		[1, 0, 0, 1, 1, 0, 0, 1],
		[1, 0, 0, 1, 0, 1, 1, 0],
		[1, 0, 0, 1, 0, 1, 0, 1],
		[1, 0, 0, 1, 0, 0, 1, 1],
		[1, 0, 0, 0, 1, 1, 1, 0],
		[1, 0, 0, 0, 1, 1, 0, 1],
		[1, 0, 0, 0, 1, 0, 1, 1],
		[1, 0, 0, 0, 0, 1, 1, 1]]
};
